[package]
name = "px4-ulog"
version = "0.6.1"
authors = [
    "Ilari Mäkimattila <ilari@auterion.com>",
    "Beat Küng <beat@px4.io>",
    "Ramón Roche <mrpollo@gmail.com>",
]
description = "PX4 ULog parsing library"
license = "MIT"
edition = "2021"
repository = "https://github.com/PX4/px4-ulog-rs"
exclude = [
    "tests/fixtures/",
    "tests/snapshots/",
    ".github/",
]

[[bin]]
name = "px4-ulog"
path = "src/main.rs"


[dependencies]
byteorder = "1"

[dev-dependencies]
criterion = "0.5"
clap = { version = "4", features = ["derive"] }
insta = { version = "1", features = ["yaml"] }
serde = { version = "1", features = ["derive"] }

[[bench]]
name = "parser"
harness = false
